services:
  drupal_v0_1:
    build:
      context: ./drupal
      dockerfile: ./Dockerfile_v0_1
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - docker-net
    environment:
      DRUPAL_SETTINS_DB_HOST: base-postgres_v0_1-1
      DRUPAL_SETTINGS_DB_NAME: drupal_v0_1
      DRUPAL_SETTINGS_DB_USER: ${DRUPAL_DB_USER}
      DRUPAL_SETTINGS_DB_PASSWORD: ${DRUPAL_DB_PWD}
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    # depends_on:
    #   - postgres_v0_1

  nginx_v0_1:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile_v0_1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - drupal_sites:/var/www/html/sites:ro # Monta solo lectura para Nginx
    depends_on:
      - drupal_v0_1

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
networks:
  docker-net:
    external: true